[package]
name = "era-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
erabasic-compat = { path = "../erabasic-compat" }
blake3.workspace = true
era-debug-protocol = { path = "../era-debug-protocol" }
era-protocol = { path = "../era-protocol" }
era-runtime-protocol = { path = "../era-runtime-protocol" }
era-runtime-save = { path = "../era-runtime-save" }
erabasic-analyzer = { path = "../erabasic-analyzer" }
erabasic-ast = { path = "../erabasic-ast" }
erabasic-bytecode = { path = "../erabasic-bytecode" }
erabasic-compiler = { path = "../erabasic-compiler" }
era-config = { path = "../era-config" }
erabasic-csv = { path = "../erabasic-csv" }
erabasic-data = { path = "../erabasic-data" }
erabasic-html = { path = "../erabasic-html" }
erabasic-hir = { path = "../erabasic-hir" }
erabasic-parser = { path = "../erabasic-parser" }
erabasic-validator = { path = "../erabasic-validator" }
erabasic-vm = { path = "../erabasic-vm" }
zstd.workspace = true
minicbor.workspace = true
serde.workspace = true
serde_json = "1.0.112"
rmp-serde.workspace = true
rayon.workspace = true
unicode-segmentation.workspace = true

[lints]
workspace = true
