[workspace]
members = [
    "crates/erabasic-ast",
    "crates/erabasic-data",
    "crates/erabasic-csv",
    "crates/erabasic-lexer",
    "crates/erabasic-parser",
    "crates/erabasic-repl",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[workspace.dependencies]
serde = { version = "1.0.210", features = ["derive"] }
