[workspace]
members = [
    "crates/era-debug-protocol",
    "crates/era-protocol",
    "crates/era-runtime-ffi",
    "crates/era-runtime-protocol",
    "crates/erabasic-ast",
    "crates/erabasic-bytecode",
    "crates/erabasic-compiler",
    "crates/erabasic-data",
    "crates/erabasic-csv",
    "crates/erabasic-hir",
    "crates/erabasic-analyzer",
    "crates/erabasic-lexer",
    "crates/erabasic-parser",
    "crates/erabasic-repl",
    "crates/erabasic-validator",
    "crates/erabasic-vm",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[workspace.dependencies]
blake3 = "1.5.5"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
minicbor = { version = "2.2.2", features = ["derive", "std"] }
