[package]
name = "erabasic-validator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
erabasic-bytecode = { path = "../erabasic-bytecode" }
erabasic-data = { path = "../erabasic-data" }
erabasic-hir = { path = "../erabasic-hir" }
serde.workspace = true

[dev-dependencies]
erabasic-csv = { path = "../erabasic-csv" }

[lints]
workspace = true
