[package]
name = "erabasic-parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
erabasic-compat = { path = "../erabasic-compat" }
erabasic-ast = { path = "../erabasic-ast" }
erabasic-lexer = { path = "../erabasic-lexer" }
serde.workspace = true

[lints]
workspace = true
