[package]
name = "era-runtime-capi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
era-protocol = { path = "../era-protocol" }
era-runtime = { path = "../era-runtime" }
era-runtime-ffi = { path = "../era-runtime-ffi" }
