[package]
name = "erabasic-vm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
erabasic-bytecode = { path = "../erabasic-bytecode" }
erabasic-data = { path = "../erabasic-data" }
erabasic-html = { path = "../erabasic-html" }
erabasic-validator = { path = "../erabasic-validator" }
regex.workspace = true
quick-xml.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_json = "1.0.112"
zstd.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[dev-dependencies]
erabasic-analyzer = { path = "../erabasic-analyzer" }
erabasic-compiler = { path = "../erabasic-compiler" }
erabasic-csv = { path = "../erabasic-csv" }

[lints]
workspace = true
