use erabasic_bytecode::HostCapability;

use super::{ExecutionBinding, HostBinding, HostRegistry, host_contract};

pub(super) fn register_hosts(
    registry: &mut HostRegistry,
    names: &[&str],
    namespace: &str,
    capability: HostCapability,
) {
    for name in names {
        let contract = host_contract(namespace, name);
        registry.register(
            *name,
            HostBinding {
                namespace: namespace.into(),
                name: name.to_ascii_lowercase(),
                abi_version: 1,
                effect: contract.effect(),
                capability,
                snapshot_capability: contract.snapshot_capability(),
                contract,
            },
        );
    }
}

pub(super) fn register_sql(registry: &mut HostRegistry) {
    register_hosts(registry, SQL, "rustyera.sql", HostCapability::Sql);
    for (name, capability, reason) in SQL_DEFERRED {
        registry.register_execution(
            *name,
            ExecutionBinding::UnsupportedCapability {
                capability: (*capability).into(),
                reason: (*reason).into(),
            },
        );
    }
}

pub(super) const INPUT: &[&str] = &[
    "WAIT",
    "WAITANYKEY",
    "FORCEWAIT",
    "TWAIT",
    "AWAIT",
    "INPUT",
    "INPUTS",
    "ONEINPUT",
    "ONEINPUTS",
    "TINPUT",
    "TINPUTS",
    "TONEINPUT",
    "TONEINPUTS",
    "TINPUTNF",
    "TINPUTSNF",
    "TONEINPUTNF",
    "TONEINPUTSNF",
    "SEQUENCEINPUT",
    "DISABLE_INPUT_MACRO",
    "ENABLE_INPUT_MACRO",
    "ENV_HAS_CAPABILITY",
    "GETPLATFORM",
    "INPUTANY",
    "BINPUT",
    "BINPUTS",
    "ONEBINPUT",
    "ONEBINPUTS",
    "INPUTMOUSEKEY",
    "__GETKEY_ACTIVE",
    "GETKEY",
    "GETKEYTRIGGERED",
    "GETTEXTBOX",
    "SETTEXTBOX",
    "CLEARTEXTBOX",
    "ISACTIVE",
    "HOTKEY_STATE",
    "HOTKEY_STATE_INIT",
    "MOUSEX",
    "MOUSEY",
    "MOUSEB",
    "FLOWINPUT",
    "FLOWINPUTS",
    "BREAKBUTTON",
];

pub(super) const TEXT: &[&str] = &[
    "PRINT",
    "PRINTL",
    "PRINTW",
    "PRINTV",
    "PRINTVL",
    "PRINTVW",
    "PRINTS",
    "PRINTSL",
    "PRINTSW",
    "PRINTFORM",
    "PRINTFORML",
    "PRINTFORMW",
    "PRINTFORMS",
    "PRINTFORMSL",
    "PRINTFORMSW",
    "PRINTC",
    "CLEARLINE",
    "REUSELASTLINE",
    "DRAWLINE",
    "BAR",
    "BARL",
    "PRINTBUTTON",
    "PRINTBUTTONC",
    "PRINTBUTTONLC",
    "PRINTPLAIN",
    "PRINTPLAINFORM",
    "PRINTSINGLE",
    "PRINTSINGLEFORM",
    "PRINTDATA",
    "PRINTDATAL",
    "PRINTDATAW",
    "HTML_PRINT",
    "HTML_PRINTC",
    "HTML_PRINTLC",
    "HTML_PRINT_ISLAND",
    "HTML_PRINT_ISLAND_CLEAR",
    "HTML_TAGSPLIT",
    "PRINT_IMG",
    "PRINT_RECT",
    "PRINT_SPACE",
    "DEBUGPRINT",
    "DEBUGPRINTL",
    "DEBUGPRINTFORM",
    "DEBUGPRINTFORML",
    "DEBUGCLEAR",
    "OUTPUTLOG",
    "GETDISPLAYLINE",
    "GETLINESTR",
    "HTML_GETPRINTEDSTR",
    "HTML_POPPRINTINGSTR",
    "LINEISEMPTY",
    "PRINTLC",
    "PRINTFORMC",
    "PRINTFORMLC",
    "PRINTSINGLEV",
    "PRINTSINGLES",
    "PRINTSINGLEFORMS",
    "PRINTCPERLINE",
    "PRINTK",
    "PRINTKL",
    "PRINTKW",
    "PRINTVK",
    "PRINTVKL",
    "PRINTVKW",
    "PRINTSK",
    "PRINTSKL",
    "PRINTSKW",
    "PRINTFORMK",
    "PRINTFORMKL",
    "PRINTFORMKW",
    "PRINTFORMSK",
    "PRINTFORMSKL",
    "PRINTFORMSKW",
    "PRINTCK",
    "PRINTLCK",
    "PRINTFORMCK",
    "PRINTFORMLCK",
    "PRINTSINGLEK",
    "PRINTSINGLEVK",
    "PRINTSINGLESK",
    "PRINTSINGLEFORMK",
    "PRINTSINGLEFORMSK",
    "PRINTDATAK",
    "PRINTDATAKL",
    "PRINTDATAKW",
    "PRINTD",
    "PRINTDL",
    "PRINTDW",
    "PRINTVD",
    "PRINTVDL",
    "PRINTVDW",
    "PRINTSD",
    "PRINTSDL",
    "PRINTSDW",
    "PRINTFORMD",
    "PRINTFORMDL",
    "PRINTFORMDW",
    "PRINTFORMSD",
    "PRINTFORMSDL",
    "PRINTFORMSDW",
    "PRINTCD",
    "PRINTLCD",
    "PRINTFORMCD",
    "PRINTFORMLCD",
    "PRINTSINGLED",
    "PRINTSINGLEVD",
    "PRINTSINGLESD",
    "PRINTSINGLEFORMD",
    "PRINTSINGLEFORMSD",
    "PRINTDATAD",
    "PRINTDATADL",
    "PRINTDATADW",
    "ASSERT",
    "THROW",
    "FORCEKANA",
    "UPCHECK",
    "CUPCHECK",
    "CUSTOMDRAWLINE",
    "DRAWLINEFORM",
    "PRINT_ABL",
    "PRINT_TALENT",
    "PRINT_MARK",
    "PRINT_EXP",
    "PRINT_PALAM",
    "PRINT_ITEM",
    "PRINT_SHOPITEM",
    "PRINTN",
    "PRINTVN",
    "PRINTSN",
    "PRINTFORMN",
    "PRINTFORMSN",
    "SETCOLOR",
    "SETCOLORBYNAME",
    "RESETCOLOR",
    "SETBGCOLOR",
    "SETBGCOLORBYNAME",
    "RESETBGCOLOR",
    "FONTBOLD",
    "FONTITALIC",
    "FONTREGULAR",
    "FONTSTYLE",
    "ALIGNMENT",
    "SETFONT",
    "REDRAW",
    "SKIPDISP",
    "NOSKIP",
    "ENDNOSKIP",
    "SKIPLOG",
    "TOOLTIP_SETCOLOR",
    "TOOLTIP_SETDELAY",
    "TOOLTIP_SETDURATION",
    "TOOLTIP_SETFONT",
    "TOOLTIP_SETFONTSIZE",
    "TOOLTIP_CUSTOM",
    "TOOLTIP_FORMAT",
    "TOOLTIP_IMG",
    "CURRENTALIGN",
    "CURRENTREDRAW",
    "GETBGCOLOR",
    "GETCOLOR",
    "GETDEFBGCOLOR",
    "GETDEFCOLOR",
    "GETFOCUSCOLOR",
    "GETFONT",
    "GETSTYLE",
    "HTML_STRINGLEN",
    "HTML_STRINGLINES",
    "HTML_ESCAPE",
    "HTML_SUBSTRING",
    "HTML_TOPLAINTEXT",
    "PRINTCLENGTH",
    "BARSTR",
    "MONEYSTR",
    "TOSTR",
    "TOFULL",
    "TOHALF",
    "MESSKIP",
    "MOUSESKIP",
    "ISSKIP",
];

pub(super) const CLOCK: &[&str] = &["GETTIME", "GETTIMES", "GETMILLISECOND", "GETSECOND"];

pub(super) const GRAPHICS: &[&str] = &[
    "SETBGIMAGE",
    "CLEARBGIMAGE",
    "REMOVEBGIMAGE",
    "CHKFONT",
    "CLIENTHEIGHT",
    "CLIENTWIDTH",
    "GCREATE",
    "GCREATEFROMFILE",
    "GDISPOSE",
    "GLOAD",
    "GSAVE",
    "GDRAWG",
    "GDRAWGWITHMASK",
    "GDRAWGWITHROTATE",
    "GDRAWLINE",
    "GDRAWSPRITE",
    "GDRAWTEXT",
    "GFILLRECTANGLE",
    "G_POLYGON_DRAW",
    "G_POLYGON_FILL",
    "G_POLYGON_POINT_ADD",
    "G_POLYGON_POINT_CLEAR",
    "SPRITECREATE",
    "SPRITECREATEFROMFILE",
    "SPRITEANIMECREATE",
    "SPRITEANIMEADDFRAME",
    "SPRITEDISPOSE",
    "SPRITEDISPOSEALL",
    "SPRITEMOVE",
    "SPRITESETPOS",
    "SPRITEWIDTH",
    "SPRITEHEIGHT",
    "BITMAP_CACHE_ENABLE",
    "MOVETEXTBOX",
    "RESUMETEXTBOX",
    "CBGCLEAR",
    "CBGCLEARBUTTON",
    "CBGREMOVEBMAP",
    "CBGREMOVERANGE",
    "CBGSETBMAPG",
    "CBGSETBUTTONSPRITE",
    "CBGSETG",
    "CBGSETSPRITE",
    "SETIMAGELAYER",
    "SETIMAGELAYERL",
    "CLEARIMAGELAYER",
    "CLEARIMAGELAYER_ALL",
    "EXISTSIMAGELAYER",
    "GETLINEY",
    "GCLEAR",
    "GCREATED",
    "GHEIGHT",
    "GWIDTH",
    "GSETBRUSH",
    "GSETCOLOR",
    "GSETFONT",
    "GSETPEN",
    "GDASHSTYLE",
    "GGETBRUSH",
    "GGETCOLOR",
    "GGETFONT",
    "GGETPEN",
    "GGETTEXTSIZE",
    "GGETFONTSIZE",
    "GGETFONTSTYLE",
    "GGETPENWIDTH",
    "SPRITECREATED",
    "SPRITEGETCOLOR",
    "SPRITEPOSX",
    "SPRITEPOSY",
    "SETANIMETIMER",
    "GETANIMETIMER",
    "TEXT_BGC_ON",
    "TEXT_BGC_OFF",
];

pub(super) const AUDIO: &[&str] = &[
    "PLAYSOUND",
    "STOPSOUND",
    "PLAYBGM",
    "STOPBGM",
    "SETSOUNDVOLUME",
    "SETBGMVOLUME",
    "EXISTSOUND",
    "GETSOUNDORBGMINFO",
    "ISPLAYINGSOUND",
    "SOUNDCONTROL",
    "ISPLAYINGBGM",
    "BGMCONTROL",
];

pub(super) const STORAGE: &[&str] = &[
    "SAVEDATA",
    "LOADDATA",
    "DELDATA",
    "SAVEGLOBAL",
    "LOADGLOBAL",
    "SAVEVAR",
    "LOADVAR",
    "SAVECHARA",
    "LOADCHARA",
    "SAVETEXT",
    "LOADTEXT",
    "EXISTFILE",
    "ENUMFILES",
    "FIND_CHARADATA",
    "OUTPUTLOG",
    "CHKDATA",
    "CHKCHARADATA",
    "SAVENOS",
    "PUTFORM",
    "RESETDATA",
    "RESETGLOBAL",
];

pub(super) const SQL: &[&str] = &[
    "SQL_CONNECT",
    "SQL_DISCONNECT",
    "SQL_EXECUTE_NONQUERY",
    "SQL_P_EXECUTE_NONQUERY",
    "SQL_EXECUTE_SCALAR_LONG",
    "SQL_EXECUTE_SCALAR_STRING",
    "SQL_P_EXECUTE_SCALAR_LONG",
    "SQL_P_EXECUTE_SCALAR_STRING",
    "SQL_EXECUTE_READER",
    "SQL_P_EXECUTE_READER",
    "SQL_READER_READ",
    "SQL_READER_GET_LONG",
    "SQL_READER_GET_STRING",
    "SQL_READER_ISNULL",
    "SQL_READER_CLOSE",
    "SQL_IMPORT_MAP_XML",
];

pub(super) const SQL_DEFERRED: &[(&str, &str, &str)] = &[
    (
        "SQL_CONNECTION_OPEN",
        "rustyera.sql.connection-open@future",
        "connection-open observation is outside the safe SQL v1 subset",
    ),
    (
        "SQL_READER_GET_FLOAT",
        "rustyera.sql.float@future",
        "Float SQL values require the batch-6 bit-exact Float contract",
    ),
    (
        "SQL_EXECUTE_SCALAR_FLOAT",
        "rustyera.sql.float@future",
        "Float SQL values require the batch-6 bit-exact Float contract",
    ),
    (
        "SQL_P_EXECUTE_SCALAR_FLOAT",
        "rustyera.sql.float@future",
        "Float SQL values require the batch-6 bit-exact Float contract",
    ),
    (
        "SQL_ESCAPE",
        "rustyera.sql.escape@future",
        "SQL text escaping is not part of parameterized safe SQL v1",
    ),
    (
        "SQL_IMPORT_DT_XML",
        "rustyera.sql.dt-xml@future",
        "DT XML import is deferred beyond safe SQL v1",
    ),
    (
        "SQL_EXPORT_MAP_XML",
        "rustyera.sql.xml-export@future",
        "XML export is deferred beyond safe SQL v1",
    ),
    (
        "SQL_EXPORT_DT_XML",
        "rustyera.sql.xml-export@future",
        "XML export is deferred beyond safe SQL v1",
    ),
    (
        "SQL_IMPORT_XML_CUSTOM",
        "rustyera.sql.custom-xml@future",
        "custom XML import is deferred beyond safe SQL v1",
    ),
];

pub(super) const SYSTEM: &[&str] = &[
    "BEGIN",
    "FORCE_BEGIN",
    "SAVEGAME",
    "LOADGAME",
    "DOTRAIN",
    "QUIT",
    "QUIT_AND_RESTART",
    "FORCE_QUIT",
    "FORCE_QUIT_AND_RESTART",
    "CALLTRAIN",
    "STOPCALLTRAIN",
    "GETMEMORYUSAGE",
    "CLEARMEMORY",
    "GETCONFIG",
    "GETCONFIGS",
    "VARSIZE",
    "EXISTFUNCTION",
    "EXISTVAR",
    "GETDOINGFUNCTION",
    "ENUMFUNCBEGINSWITH",
    "ENUMFUNCENDSWITH",
    "ENUMFUNCWITH",
    "ENUMVARBEGINSWITH",
    "ENUMVARENDSWITH",
    "ENUMVARWITH",
];

pub(super) const NETWORK: &[&str] = &["UPDATECHECK"];
