[package]
name = "era-runtime-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
erabasic-compat = { path = "../erabasic-compat" }
era-protocol = { path = "../era-protocol" }
erabasic-html = { path = "../erabasic-html" }
minicbor.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json = "1.0.112"

[lints]
workspace = true
