[package]
name = "erabasic-bytecode"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
erabasic-ast = { path = "../erabasic-ast" }
erabasic-compat = { path = "../erabasic-compat" }
blake3.workspace = true
erabasic-data = { path = "../erabasic-data" }
erabasic-hir = { path = "../erabasic-hir" }
rayon.workspace = true
serde.workspace = true
serde_json = "1.0.112"

[dev-dependencies]
erabasic-csv = { path = "../erabasic-csv" }

[lints]
workspace = true
