[package]
name = "erabasic-analyzer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
erabasic-ast = { path = "../erabasic-ast" }
erabasic-csv = { path = "../erabasic-csv" }
erabasic-data = { path = "../erabasic-data" }
erabasic-hir = { path = "../erabasic-hir" }
erabasic-lexer = { path = "../erabasic-lexer" }
erabasic-parser = { path = "../erabasic-parser" }
encoding_rs.workspace = true
rayon.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json = "1.0.112"

[lints]
workspace = true
